### ISSUE TITLE
区块浏览器内容显示不全

### ISSUE THREAD

**Issue by zoujinbin** [gxchain/gxchain-explorer#25]
我使用默认配置连上公信链，浏览器打开刚区块浏览器显示是正常的。但修改了config/index.js之后连上自己搭建的私有链，打开区块浏览器，显示如下图（未显示区块信息、见证人信息等）。想请教需要修改哪个配置文件，又是如何修改？
![error3](https://user-images.githubusercontent.com/39855077/43816049-76f0cc00-9b05-11e8-8b68-9b44dbfc68f5.jpg)
我改的index.js如下图（dev也是用的相同ip和端口）
![error4](https://user-images.githubusercontent.com/39855077/43816164-f9eb6bc4-9b05-11e8-845c-e44dff9fc211.jpg)

**Comment by lanhaoxiang** [comment]
需要分析下日志
