### ISSUE TITLE
区块链浏览器，查看合约数据表，切换数据表会自动切回

### ISSUE THREAD

**Issue by Morse1113** [gxchain/gxchain-explorer#31]
例如
https://block.gxb.io/#/account/genesis
点击数据表下拉框，由characount数据表切换之character表后，不做任何操作，2秒后会自动切回characount数据表，影响体验。

**Comment by lanhaoxiang** [comment]
收到，麻烦在下方提供下主链账号

**Comment by Morse1113** [comment]
morse-liu

**Comment by lanhaoxiang** [comment]
fixed
