### ISSUE TITLE
区块浏览器浏览table不到数据

### ISSUE THREAD

**Issue by baidang201** [gxchain/gxchain-explorer#33]
**Describe the bug**
1 测试网络区块浏览器无法查到card3上的userinfo表的数据，但实际上userinfo表是有数据的.

2 测试网络下，cli_wallet使用命令行
2.1get_table_rows card3 userinfo 0 100
发现没有数据

 2.2get_table_rows_ex card3 userinfo {"lower_bound":0,"upper_bound":-1,"limit":20}
是有数据的

**To Reproduce**
1 打开浏览器，导航到到 https://testnet.explorer.gxchain.org/#/account/card3
2 查看数据表userinfo,
3 发现userinfo内容是空的

**Expected behavior**
期望区块浏览器可以查到table里面的数据

**Screenshots**
![image](https://user-images.githubusercontent.com/3405789/54657982-6a7d6300-4b06-11e9-96ca-5dde3031ad0f.png)

![image](https://user-images.githubusercontent.com/3405789/54657941-4c176780-4b06-11e9-8e76-85fcb6993d96.png)

![image](https://user-images.githubusercontent.com/3405789/54657930-40c43c00-4b06-11e9-9f0a-c7018eb3bb66.png)

**Desktop (please complete the following information):**
 - OS:win10 家庭版
 - chrome: 72.0.3626.121（正式版本） （64 位）

**Additional context**
```
发现前端https://github.com/gxchain/gxchain-explorer 是用get_table_rows接口
loadTableData (page) {
                const pageSize = 10;
                Apis.instance().db_api().exec('get_table_rows', [
                    this.account_info.name, // contract_name
                    this.current_table.name, // table_name
                    pageSize * page, // start
                    pageSize // limit
                ])
```			
建议用get_table_rows_ex查询

**Your GXChain Wallet Account**
bai201

**Comment by lanhaoxiang** [comment]
fixed by 0cb150489a01847961c6912c183840255e760875
