### ISSUE TITLE
explorer Suggest

### ISSUE THREAD

**Issue by yanwankun** [gxchain/gxchain-explorer#38]
* User payment information display
> Now when the browser displays the transaction data, it only shows the parameters related to the call contract. Some contracts are the supported payment amount, but the data of the payment amount is not displayed. Sometimes the development or the user is very concerned about the payment amount. , so it is recommended to add a payment information display. When the contract operation is invoked, if there is a payment amount, the amount information paid by the user is displayed.

**Comment by xzshinan** [comment]
you can see payment information in Transaction Info.

eg: https://block.gxb.io/#/transaction/8870628dd8bedc8f96a80df32b7c579a7a813904

**Comment by lanhaoxiang** [comment]
@xLogic92 So let's show payment info if `asset.amount>0` when calling contract
