### ISSUE TITLE
Can the history balance be displayed in the history transaction record list?

### ISSUE THREAD

**Issue by xzshinan** [gxchain/gxchain-explorer#40]
Can the history balance be displayed in the history transaction record list?

**Comment by xLogic92** [comment]
Can u describe more detail?

**Comment by xzshinan** [comment]
![2 pic](https://user-images.githubusercontent.com/7299894/62186159-c058f600-b397-11e9-84cb-1ff52b4ee741.jpg)

Show the balance~ 

=============

如果在计算全历史交易记录的时候，这个balance可以顺道算下的话~ 

这样的话，相当于可以容易拿到历史余额~  

只是一个想法~
